# -*- coding: utf-8 -*-
"""YOLOV4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-uyLs7VigS6RlSiiOwVA2UFBfcVDY8d

**Connect google drive**
"""

# Check if NVIDIA GPU is enabled
!nvidia-smi

from google.colab import drive
drive.mount('/content/gdrive')
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

"""**1) Clone, configure & compile Darknet**


"""

# Clone
!git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
# Configure
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile

# Compile
!make

"""**2) Configure yolov4.cfg file**"""

# Make a copy of yolov4.cfg
!cp cfg/yolov4.cfg cfg/yolov4_training.cfg

# Change lines in yolov4.cfg file
!sed -i 's/subdivisions=8/subdivisions=64/' cfg/yolov4_training.cfg
!sed -i 's/width=608/width=416/' cfg/yolov4_training.cfg
!sed -i 's/height=608/height=416/' cfg/yolov4_training.cfg
!sed -i 's/max_batches = 500500/max_batches = 2000/' cfg/yolov4_training.cfg
!sed -i '968 s@classes=80@classes=1@' cfg/yolov4_training.cfg
!sed -i '1056 s@classes=80@classes=1@' cfg/yolov4_training.cfg
!sed -i '1144 s@classes=80@classes=1@' cfg/yolov4_training.cfg
!sed -i '961 s@filters=255@filters=18@' cfg/yolov4_training.cfg
!sed -i '1049 s@filters=255@filters=18@' cfg/yolov4_training.cfg
!sed -i '1137 s@filters=255@filters=18@' cfg/yolov4_training.cfg

"""**3) Create .names and .data files**"""

!echo -e 'Pothole' > data/obj.names
!echo -e 'classes= 1\ntrain  = data/train.txt\nvalid  = data/test.txt\nnames = data/obj.names\nbackup = /mydrive/yolov3' > data/obj.data

"""**4) Save yolov4_training.cfg and obj.names files in Google drive**"""

!cp cfg/yolov4_training.cfg /mydrive/yolov3/yolov4_testing.cfg
!cp data/obj.names /mydrive/yolov3/classes.txt

"""**5) Create a folder and unzip image dataset**"""

!mkdir data/obj
!unzip /mydrive/yolov3/images2.zip -d data/obj

"""**6) Create train.txt file**"""

import glob
images_list = glob.glob("data/obj/*.jpg")
with open("data/train.txt", "w") as f:
    f.write("\n".join(images_list))

"""**7) Download pre-trained weights for the convolutional layers file**"""

#!wget https://pjreddie.com/media/files/yolov4.conv.137
# Download the yolov4 pre-trained weights file
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

"""**8) Start training**"""

!./darknet detector train data/obj.data cfg/yolov4_training.cfg yolov4.conv.137 -dont_show
# Uncomment below and comment above to re-start your training from last saved weights
#!./darknet detector train data/obj.data cfg/yolov3_training.cfg /mydrive/yolov3/yolov3_training_last.weights -dont_show

"""# Reference:"""

# https://github.com/luisaugustos/Pothole-Recognition (Pothole Recognition using Drone Images)

# https://github.com/AlexeyAB/darknet (AlexeyAB)

# https://www.youtube.com/watch?v=yGMZOD44GrI (Object Detection Using YOLO v4 on Custom Dataset | Practical Implementation- Code With Aarohi)